spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: lkker
    password: lkker123456
    virtual-host: lkker
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        auto-startup: true
        concurrency: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///laiyuetest?autoReconnect=true&useSSL=false&characterEncoding=utf8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

